version: '3'

services:
  user-service:
    image: apm-java/app:1.0.0
    build:
      context: ../
      dockerfile: docker/java/Dockerfile
      args:
        - "JAR_PATH=target/spring-apm-example-0.0.1-SNAPSHOT.jar"
    environment:
      - "JAR_NAME=spring-apm-example-0.0.1-SNAPSHOT.jar"
      - "JVM_OPTIONS="
      - "ELASTIC_APM_SERVICE_NAME=user-service"
      - "ELASTIC_APM_APPLICATION_PACKAGES=com.example.restapi"
      - "ELASTIC_APM_SERVER_URLS=http://apm:8200"
      - "ELASTIC_APM_TRACE_METHODS=com.example.restapi.*"
    ports:
      - 8080:8080
    links:
      - apm

  kibana:
    image: kibana:7.6.0
    environment:
      - "LOGGING_QUIET=true"
    ports:
      - 5601:5601
    links:
      - elasticsearch

  elasticsearch:
    image: apm-java/elasticsearch:1.0.0
    build:
      context: elasticsearch
      dockerfile: Dockerfile
    environment:
      - cluster.name=apm-java
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - data01:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  apm:
    image: apm-java/apm-server:1.0.0
    command: --strict.perms=false
    build:
      context: apm-server
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    links:
      - elasticsearch
      - kibana

volumes:
  data01:
    driver: local